// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    alerts: {
        name: "alerts";
        parameters: {
          /** any - use sql.*() */
          mm: SQLTypeMarker;
          /** any - use sql.*() */
          ss: SQLTypeMarker;
          /** INT - use sql.int() */
          max_rows: SQLNumberMarker;
        };
        result: unknown;
      };
    cameras_online: {
        name: "cameras_online";
        parameters: Record<string, never>;
        result: unknown;
      };
    data_search: {
        name: "data_search";
        parameters: {
          /** any - use sql.*() */
          mm: SQLTypeMarker;
          /** any - use sql.*() */
          ss: SQLTypeMarker;
          /** STRING - use sql.string() */
          search: SQLStringMarker;
          /** INT - use sql.int() */
          max_rows: SQLNumberMarker;
        };
        result: unknown;
      };
    detections_hourly: {
        name: "detections_hourly";
        parameters: Record<string, never>;
        result: unknown;
      };
    detections_recent: {
        name: "detections_recent";
        parameters: {
          /** INT - use sql.int() */
          max_rows: SQLNumberMarker;
        };
        result: unknown;
      };
    detections_since: {
        name: "detections_since";
        parameters: {
          /** any - use sql.*() */
          mm: SQLTypeMarker;
          /** any - use sql.*() */
          ss: SQLTypeMarker;
          /** TIMESTAMP - use sql.timestamp() */
          since: SQLTimestampMarker;
        };
        result: unknown;
      };
    detections_summary: {
        name: "detections_summary";
        parameters: {
          /** STRING - use sql.string() */
          period: SQLStringMarker;
        };
        result: unknown;
      };
    device_history: {
        name: "device_history";
        parameters: {
          /** STRING - use sql.string() */
          deviceId: SQLStringMarker;
          /** any - use sql.*() */
          mm: SQLTypeMarker;
          /** INT - use sql.int() */
          hours: SQLNumberMarker;
        };
        result: unknown;
      };
    device_stats: {
        name: "device_stats";
        parameters: Record<string, never>;
        result: unknown;
      };
    devices: {
        name: "devices";
        parameters: {
          /** any - use sql.*() */
          mm: SQLTypeMarker;
          /** any - use sql.*() */
          ss: SQLTypeMarker;
        };
        result: unknown;
      };
    inventory_pizza: {
        name: "inventory_pizza";
        parameters: {
          /** STRING - use sql.string() */
          storeId: SQLStringMarker;
          /** any - use sql.*() */
          mm: SQLTypeMarker;
        };
        result: unknown;
      };
    inventory_truck: {
        name: "inventory_truck";
        parameters: {
          /** STRING - use sql.string() */
          storeId: SQLStringMarker;
          /** any - use sql.*() */
          mm: SQLTypeMarker;
        };
        result: unknown;
      };
    pipeline_frames: {
        name: "pipeline_frames";
        parameters: {
          /** any - use sql.*() */
          mm: SQLTypeMarker;
          /** any - use sql.*() */
          ss: SQLTypeMarker;
          /** INT - use sql.int() */
          max_rows: SQLNumberMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          file_name: string;
          /** @sqlType STRING */
          source_path: string;
          /** @sqlType STRING */
          camera: string;
          /** @sqlType STRING */
          frame_ts: string;
          /** @sqlType STRING */
          pipeline_ts: string;
          /** @sqlType STRING */
          bucket_ts: string;
          /** @sqlType BIGINT */
          size_bytes: number;
          /** @sqlType INT */
          num_detections: number;
          /** @sqlType STRING */
          detections_json: string;
        }>;
      };
    pipeline_stats: {
        name: "pipeline_stats";
        parameters: {
          /** any - use sql.*() */
          mm: SQLTypeMarker;
          /** any - use sql.*() */
          ss: SQLTypeMarker;
        };
        result: Array<{
          /** @sqlType BIGINT */
          raw_frames: number;
          /** @sqlType BIGINT */
          deduped_frames: number;
          /** @sqlType BIGINT */
          processed_frames: number;
          /** @sqlType BIGINT */
          total_detections: number;
          /** @sqlType BIGINT */
          cameras_active: number;
          /** @sqlType STRING */
          last_processed_at: string;
        }>;
      };
    plate_distribution: {
        name: "plate_distribution";
        parameters: {
          /** STRING - use sql.string() */
          period: SQLStringMarker;
        };
        result: unknown;
      };
    plate_recent: {
        name: "plate_recent";
        parameters: {
          /** INT - use sql.int() */
          max_rows: SQLNumberMarker;
        };
        result: unknown;
      };
    plate_stats: {
        name: "plate_stats";
        parameters: Record<string, never>;
        result: unknown;
      };
    vehicle_traffic: {
        name: "vehicle_traffic";
        parameters: Record<string, never>;
        result: unknown;
      };
  }
}
