// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    alerts: {
        name: "alerts";
        parameters: {
          /** any - use sql.*() */
          mm: SQLTypeMarker;
          /** any - use sql.*() */
          ss: SQLTypeMarker;
          /** INT - use sql.int() */
          max_rows: SQLNumberMarker;
        };
        result: Array<{
          /** @sqlType BIGINT */
          id: number;
          /** @sqlType STRING */
          ruleId: string;
          /** @sqlType STRING */
          message: string;
          /** @sqlType STRING */
          severity: string;
          /** @sqlType STRING */
          storeId: string;
          /** @sqlType STRING */
          storeName: string;
          /** @sqlType STRING */
          ts: string;
          /** @sqlType BOOLEAN */
          acknowledged: boolean;
        }>;
      };
    cameras_online: {
        name: "cameras_online";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          hour: string;
          /** @sqlType BIGINT */
          cameras: number;
        }>;
      };
    data_search: {
        name: "data_search";
        parameters: {
          /** any - use sql.*() */
          mm: SQLTypeMarker;
          /** any - use sql.*() */
          ss: SQLTypeMarker;
          /** STRING - use sql.string() */
          search: SQLStringMarker;
          /** INT - use sql.int() */
          max_rows: SQLNumberMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          kind: string;
          /** @sqlType BIGINT */
          id: number;
          /** @sqlType STRING */
          label: string;
          /** @sqlType STRING */
          store: string;
          /** @sqlType STRING */
          ts: string;
          /** @sqlType INT */
          confidence: number;
        }>;
      };
    detections_hourly: {
        name: "detections_hourly";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          hour: string;
          /** @sqlType BIGINT */
          count: number;
        }>;
      };
    detections_recent: {
        name: "detections_recent";
        parameters: {
          /** INT - use sql.int() */
          max_rows: SQLNumberMarker;
        };
        result: Array<{
          /** @sqlType BIGINT */
          id: number;
          /** @sqlType STRING */
          type: string;
          /** @sqlType STRING */
          location: string;
          /** @sqlType STRING */
          time: string;
          /** @sqlType INT */
          confidence: number;
        }>;
      };
    detections_since: {
        name: "detections_since";
        parameters: {
          /** any - use sql.*() */
          mm: SQLTypeMarker;
          /** any - use sql.*() */
          ss: SQLTypeMarker;
          /** TIMESTAMP - use sql.timestamp() */
          since: SQLTimestampMarker;
        };
        result: Array<{
          /** @sqlType BIGINT */
          id: number;
          /** @sqlType STRING */
          frame_id: string;
          /** @sqlType STRING */
          ts: string;
          /** @sqlType STRING */
          store_id: string;
          /** @sqlType STRING */
          label: string;
          /** @sqlType BIGINT */
          class_id: number;
          /** @sqlType DOUBLE */
          confidence: number;
          /** @sqlType ARRAY<BIGINT> */
          bbox: unknown[];
        }>;
      };
    detections_summary: {
        name: "detections_summary";
        parameters: {
          /** STRING - use sql.string() */
          period: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          object: string;
          /** @sqlType BIGINT */
          count: number;
          /** @sqlType STRING */
          trend: string;
          /** @sqlType STRING */
          icon: string;
          /** @sqlType STRING */
          color: string;
        }>;
      };
    device_history: {
        name: "device_history";
        parameters: {
          /** STRING - use sql.string() */
          deviceId: SQLStringMarker;
          /** any - use sql.*() */
          mm: SQLTypeMarker;
          /** INT - use sql.int() */
          hours: SQLNumberMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          time: string;
          /** @sqlType DOUBLE */
          temperature: number;
          /** @sqlType DOUBLE */
          humidity: number;
        }>;
      };
    device_stats: {
        name: "device_stats";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType BIGINT */
          normalCount: number;
          /** @sqlType BIGINT */
          warningCount: number;
          /** @sqlType BIGINT */
          criticalCount: number;
          /** @sqlType STRING */
          avgTemp: string;
          /** @sqlType BIGINT */
          totalDevices: number;
        }>;
      };
    devices: {
        name: "devices";
        parameters: {
          /** any - use sql.*() */
          mm: SQLTypeMarker;
          /** any - use sql.*() */
          ss: SQLTypeMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          id: string;
          /** @sqlType STRING */
          name: string;
          /** @sqlType STRING */
          location: string;
          /** @sqlType DOUBLE */
          currentTemp: number;
          /** @sqlType STRING */
          status: string;
          /** @sqlType STRING */
          lastUpdate: string;
        }>;
      };
    inventory_pizza: {
        name: "inventory_pizza";
        parameters: {
          /** STRING - use sql.string() */
          storeId: SQLStringMarker;
          /** any - use sql.*() */
          mm: SQLTypeMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          time: string;
          /** @sqlType DOUBLE */
          percentage: number;
        }>;
      };
    inventory_truck: {
        name: "inventory_truck";
        parameters: {
          /** STRING - use sql.string() */
          storeId: SQLStringMarker;
          /** any - use sql.*() */
          mm: SQLTypeMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          time: string;
          /** @sqlType DOUBLE */
          value: number;
        }>;
      };
    pipeline_frames: {
        name: "pipeline_frames";
        parameters: {
          /** any - use sql.*() */
          mm: SQLTypeMarker;
          /** any - use sql.*() */
          ss: SQLTypeMarker;
          /** INT - use sql.int() */
          max_rows: SQLNumberMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          file_name: string;
          /** @sqlType STRING */
          source_path: string;
          /** @sqlType STRING */
          camera: string;
          /** @sqlType STRING */
          frame_ts: string;
          /** @sqlType STRING */
          pipeline_ts: string;
          /** @sqlType STRING */
          bucket_ts: string;
          /** @sqlType BIGINT */
          size_bytes: number;
          /** @sqlType INT */
          num_detections: number;
          /** @sqlType STRING */
          detections_json: string;
        }>;
      };
    pipeline_stats: {
        name: "pipeline_stats";
        parameters: {
          /** any - use sql.*() */
          mm: SQLTypeMarker;
          /** any - use sql.*() */
          ss: SQLTypeMarker;
        };
        result: Array<{
          /** @sqlType BIGINT */
          raw_frames: number;
          /** @sqlType BIGINT */
          deduped_frames: number;
          /** @sqlType BIGINT */
          processed_frames: number;
          /** @sqlType BIGINT */
          total_detections: number;
          /** @sqlType BIGINT */
          cameras_active: number;
          /** @sqlType STRING */
          last_processed_at: string;
        }>;
      };
    plate_distribution: {
        name: "plate_distribution";
        parameters: {
          /** STRING - use sql.string() */
          period: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          state: string;
          /** @sqlType STRING */
          name: string;
          /** @sqlType BIGINT */
          count: number;
          /** @sqlType DOUBLE */
          percentage: number;
          /** @sqlType STRING */
          color: string;
        }>;
      };
    plate_recent: {
        name: "plate_recent";
        parameters: {
          /** INT - use sql.int() */
          max_rows: SQLNumberMarker;
        };
        result: Array<{
          /** @sqlType BIGINT */
          id: number;
          /** @sqlType STRING */
          state: string;
          /** @sqlType STRING */
          plateNumber: string;
          /** @sqlType STRING */
          location: string;
          /** @sqlType STRING */
          time: string;
          /** @sqlType INT */
          confidence: number;
        }>;
      };
    plate_stats: {
        name: "plate_stats";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType BIGINT */
          totalDetected: number;
          /** @sqlType BIGINT */
          uniqueStates: number;
          /** @sqlType INT */
          averagePerHour: number;
          /** @sqlType STRING */
          trend: string;
        }>;
      };
    vehicle_traffic: {
        name: "vehicle_traffic";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          hour: string;
          /** @sqlType BIGINT */
          vehicles: number;
        }>;
      };
  }
}
