// Auto-generated by AppKit - DO NOT EDIT
// Generated from serving endpoint OpenAPI schemas
import "@databricks/appkit";
import "@databricks/appkit-ui/react";

declare module "@databricks/appkit" {
  interface ServingEndpointRegistry {
    default: {
      request: {
        messages?: {
          role?: "user" | "assistant";
          content?: string;
        }[];
        /** @openapi integer, nullable */
        n?: number | null;
        max_tokens?: number;
        /** @openapi double, nullable */
        top_p?: number | null;
        reasoning_effort?: "low" | "medium" | "high" | null;
        /** @openapi double, nullable */
        temperature?: number | null;
        stop?: string | string[] | null;
        /** @openapi integer, nullable */
        top_k?: number | null;
      };
      response: {
        model?: string;
        choices?: {
          index?: number;
          message?: {
            role?: "user" | "assistant";
            content?: string;
          };
          finish_reason?: string;
        }[];
        usage?: {
          prompt_tokens?: number;
          completion_tokens?: number;
          total_tokens?: number;
        } | null;
        object?: string;
        id?: string;
        created?: number;
      };
      chunk: {
        model?: string;
        choices?: {
          index?: number;
          delta?: {
            role?: "user" | "assistant";
            content?: string;
          };
          finish_reason?: string | null;
        }[];
        object?: string;
        id?: string;
        created?: number;
      };
    };
  }
}

declare module "@databricks/appkit-ui/react" {
  interface ServingEndpointRegistry {
    default: {
      request: {
        messages?: {
          role?: "user" | "assistant";
          content?: string;
        }[];
        /** @openapi integer, nullable */
        n?: number | null;
        max_tokens?: number;
        /** @openapi double, nullable */
        top_p?: number | null;
        reasoning_effort?: "low" | "medium" | "high" | null;
        /** @openapi double, nullable */
        temperature?: number | null;
        stop?: string | string[] | null;
        /** @openapi integer, nullable */
        top_k?: number | null;
      };
      response: {
        model?: string;
        choices?: {
          index?: number;
          message?: {
            role?: "user" | "assistant";
            content?: string;
          };
          finish_reason?: string;
        }[];
        usage?: {
          prompt_tokens?: number;
          completion_tokens?: number;
          total_tokens?: number;
        } | null;
        object?: string;
        id?: string;
        created?: number;
      };
      chunk: {
        model?: string;
        choices?: {
          index?: number;
          delta?: {
            role?: "user" | "assistant";
            content?: string;
          };
          finish_reason?: string | null;
        }[];
        object?: string;
        id?: string;
        created?: number;
      };
    };
  }
}
